ClothesLine_FN/Models/TourPackege.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClothesLine_FN.Models
{
    public class TourPackege
    {
        public long Id { get; set; }
        [Required]
        public long CategoryId { get; set; }
        public virtual Category Category { get; set; }
        [Required]
        public long DestinationPlaceId { get; set; }
        public virtual DestinationPlace DestinationPlace { get; set; }
        [Required]
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string HotelName { get; set; }
        [Required]
        public decimal Cost { get; set; }
    }
}

ClothesLine_FN/Controllers/TourPackegesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClothesLine_FN.Bll;
using ClothesLine_FN.Models;
using ClothesLine_FN.Models.Context;

namespace ClothesLine_FN.Controllers
{
    public class TourPackegesController : Controller
    {
        private ClothesLine_FN_Context db = new ClothesLine_FN_Context();
        Common common = new Common();
        bool status = false;

        public PartialViewResult TourPackegesPartialDetail(int id)
        {
            TourPackege tourPackege = db.TourPackeges.Where(c => c.Id == id).FirstOrDefault();
            return PartialView("~/Views/Shared/TourPackeges/_PartialTourPackegeDetail.cshtml", tourPackege);
        }
        public PartialViewResult TourPackegesByCategory(int id)
        {
            List<TourPackege> tourPackeges = db.TourPackeges.Where(c => c.Category.Id == id).ToList();
            return PartialView("~/Views/Shared/TourPackeges/_PartialTourPackegesList.cshtml", tourPackeges);
        }
        public PartialViewResult TourPackegesByDes(int id)
        {
            List<TourPackege> tourPackeges = db.TourPackeges.Where(c => c.DestinationPlace.Id == id).ToList();
            return PartialView("~/Views/Shared/TourPackeges/_PartialTourPackegesList.cshtml", tourPackeges);
        }
        // GET: TourPackeges
        public ActionResult Index()
        {
            var tourPackeges = db.TourPackeges.Include(t => t.Category).Include(t => t.DestinationPlace);
            return View(tourPackeges.ToList());
        }

        // GET: TourPackeges/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourPackege tourPackege = db.TourPackeges.Find(id);
            if (tourPackege == null)
            {
                return HttpNotFound();
            }
            return View(tourPackege);
        }

        // GET: TourPackeges/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories.Where(c=>c.MasterCategory.Id== 12), "Id", "Name");
            ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name");
            return View();
        }

        // POST: TourPackeges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,DestinationPlaceId,Name,HotelName,Cost")] TourPackege tourPackege, HttpPostedFileBase ImageFile)
        {
            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please upload an image");
                ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
                ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
                return View(tourPackege);
            }

            bool IsValidFormat = common.ImageValidation(ImageFile);


            if (IsValidFormat == false)
            {
                ModelState.AddModelError("Image", "Only jpg, png, jpeg formates are allowed ");
                ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
                ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
                return View(tourPackege);
            }
            byte[] convertedImage = common.ConvertImage(ImageFile);
            tourPackege.Image = convertedImage;

            if (ModelState.IsValid)
            {
                db.TourPackeges.Add(tourPackege);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
            ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
            return View(tourPackege);
        }

        // GET: TourPackeges/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourPackege tourPackege = db.TourPackeges.Find(id);
            if (tourPackege == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
            ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
            return View(tourPackege);
        }

        // POST: TourPackeges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,DestinationPlaceId,Name,HotelName,Cost")] TourPackege tourPackege, HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                bool IsValidFormate = common.ImageValidation(ImageFile);
                if (IsValidFormate == false)
                {
                    ModelState.AddModelError("Image", "Only jpg, png, jpeg formates are allowed ");
                    ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
                    ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
                    return View(tourPackege);
                }
                byte[] CurrentImage = common.ConvertImage(ImageFile);
                tourPackege.Image = CurrentImage;
            }
            if (ModelState.IsValid)
            {
                db.Entry(tourPackege).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.CategoryId);
            ViewBag.DestinationPlaceId = new SelectList(db.DestinationPlaces.Where(c => c.MasterCategory.Id == 12), "Id", "Name", tourPackege.DestinationPlaceId);
            return View(tourPackege);
        }

        // GET: TourPackeges/Delete/5
        public JsonResult Delete(int id)
        {
            var TourPackegeById = db.TourPackeges.Where(m => m.Id == id).FirstOrDefault();

            if (TourPackegeById != null)
            {
                db.Entry(TourPackegeById).State = EntityState.Deleted;
                int affectedRow = db.SaveChanges();

                if (affectedRow > 0)
                {
                    status = true;
                }
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClothesLine_FN/Views/TourPackeges/Create.cshtml
@model ClothesLine_FN.Models.TourPackege

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "TourPackeges", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TourPackege</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationPlaceId, "Destination Place", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinationPlaceId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinationPlaceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HotelName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HotelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HotelName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="Image" />
                <br>
                <div class="col-md-3">
                    <div id="imagePreview" class="thumbnail" style="display:none">
                        <img class="img-responsive" id="TargetImage" />
                    </div>
                    <div class="">
                        <p id="Imagedescription"></p>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#Image").change(function () {
            var file = this.files;
            if (file && file[0]) {
                ReadImage(file[0]);
            }
        });
        var ReadImage = function (file) {
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                $("#TargetImage").attr("src", _file.target.result);
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;

                    var value = (file.size / 1024)
                    var size = Math.round(value * 100) / 100 + " KB";

                    $("#TargetImage").attr("src", _file.target.result);
                    $("#Imagedescription").html("Size: " + size + '</br>' + "Dimension: " + height + " × " + width);
                    $("#imagePreview").show();
                }
            }
        }
    </script>
}

ClothesLine_FN/Views/TourPackeges/Delete.cshtml
@model ClothesLine_FN.Models.TourPackege

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TourPackege</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationPlace.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationPlace.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClothesLine_FN/Views/TourPackeges/Details.cshtml
@model ClothesLine_FN.Models.TourPackege

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <br />
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>Packege Details</h3>
        </div>
        <div class="panel-body">
            <div class="col-xs-10">
                <div class="row vertical-align">
                    <div class="col-xs-6">
                        @if (Model.Image != null)
                        {
                            string base64Image = Convert.ToBase64String(Model.Image);
                            string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                            <img class="img-responsive img-thumbnail img-rounded" src="@Image" width="450" height="450" />
                        }
                    </div>
                    <div class="col-xs-6">
                        <table class="table table-responsive">
                            <tr>
                                <td><h4>Product Name</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Name)</h4></td>
                            </tr>
                            <tr>
                                <td><h4>Category</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Category.Name)</h4></td>
                            </tr>
                            <tr>
                                <td><h4>Destination Name</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.DestinationPlace.Name)</h4></td>
                            </tr>
                            <tr style="color:darkgreen">
                                <td><h4><b>@Html.DisplayNameFor(model => model.Cost)</b></h4></td>
                                <td><h4><b>@Html.DisplayFor(model => model.Cost)</b></h4></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-sm btn-primary" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-sm btn-info" })
</p>

ClothesLine_FN/Views/TourPackeges/Edit.cshtml
@model ClothesLine_FN.Models.TourPackege

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "TourPackeges", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TourPackege</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationPlaceId, "Destination Place", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinationPlaceId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinationPlaceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Package Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HotelName, "Hotel Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HotelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HotelName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <input type="file" name="ImageFile" id="Image" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                <br />
                @if (Model.Image != null)
                {
                    string base64Image = Convert.ToBase64String(Model.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" class="img-responsive" id="TargetImage" height="150" width="150" />
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        //this is for showing image immediately:
        $("#Image").change(function () {
            var file = this.files;
            if (file && file[0]) {
                ReadImage(file[0]);
            }
        });
        var ReadImage = function (file) {
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                $("#TargetImage").attr("src", _file.target.result);
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;

                    var value = (file.size / 1024)
                    var size = Math.round(value * 100) / 100 + " KB";

                    $("#TargetImage").attr("src", _file.target.result);
                    $("#Imagedescription").html("Size: " + size + '</br>' + "Dimension: " + height + " × " + width);
                    $("#imagePreview").show();
                }
            }
        }
    </script>
}

ClothesLine_FN/Views/TourPackeges/Index.cshtml
@model IEnumerable<ClothesLine_FN.Models.TourPackege>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-sm btn-primary" })
</p>
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <th>
            Category Name
        </th>
        <th>
            Destination Place
        </th>
        <th>
            Package Name
        </th>
        <th>
            Hotel Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="DelRow_@item.Id">
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationPlace.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelName)
            </td>
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="100" height="100" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-primary" })
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                <a class="btn btn-sm btn-danger delete_link" href="#" onclick="GetDeleteId(@item.Id)">Delete</a>
            </td>
        </tr>
    }

</table>
@Html.Hidden("DeleteId")
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>

                <h4 class="modal-title">Delete Cofirmation</h4>
            </div>
            <div class="modal-body">
                <h5>Are you sure you want to delete this item?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <input type="button" class="btn btn-danger" value="Delete" id="btnConfirmDelete" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var GetDeleteId = function (Id) {
            $("#DeleteId").val(Id);
            $("#myModal").modal("show");
        }
        $("#btnConfirmDelete").on("click", function () {
            var deleteId = $("#DeleteId").val();
            $.ajax({
                url: "/TourPackeges/Delete",
                data: { id: deleteId },
                method: "post",
                success: function (response) {
                    if (response == 1) {
                        $("#myModal").modal("hide");
                        $("#DelRow_" + deleteId).remove();
                    }
                }
            })
        })
    </script>
}