ClothesLine_FN/Models/WomansProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClothesLine_FN.Models
{
    public class WomansProduct
    {
        public long Id { get; set; }

        [Required]
        public long BrandId { get; set; }
        public virtual Brand Brand { get; set; }

        [Required]
        public long SizeId { get; set; }
        public virtual Size Size { get; set; }

        [Required]
        public long ColourId { get; set; }
        public virtual Colour Colour { get; set; }

        [Required]
        public string Name { get; set; }
        public byte[] Image { get; set; }

        [Required]
        public decimal Price { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(maximumLength: 1000, ErrorMessage = "Description can not be more then 1000 characters")]
        public string Description { get; set; }

    }
}

ClothesLine_FN/Controllers/WomansProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClothesLine_FN.Bll;
using ClothesLine_FN.Models;
using ClothesLine_FN.Models.Context;

namespace ClothesLine_FN.Controllers
{
    public class WomansProductsController : Controller
    {
        private ClothesLine_FN_Context db = new ClothesLine_FN_Context();
        Common common = new Common();
        bool status = false;
        // GET: WomansProducts
        public PartialViewResult WomansProductPartialDetail(int id)
        {
            WomansProduct product = db.WomansProducts.Where(c => c.Id == id).FirstOrDefault();
            return PartialView("~/Views/Shared/WomansProduct/WomansProductPartialDetail.cshtml", product);
        }
        public PartialViewResult WomansProductByCategoriy(int id)
        {
            List<WomansProduct> products = db.WomansProducts.Where(c => c.Brand.Category.Id == id).ToList();
            return PartialView("~/Views/Shared/WomansProduct/_FilteredWomansProductList.cshtml", products);
        }
        public PartialViewResult WomansProductByBrand(int id)
        {
            List<WomansProduct> products = db.WomansProducts.Where(c => c.Brand.Id == id).ToList();
            return PartialView("~/Views/Shared/WomansProduct/_FilteredWomansProductList.cshtml", products);
        }

        public PartialViewResult WomansProductByPrice(int id)
        {
            Price price = db.Prices.Where(c => c.Id == id).FirstOrDefault();
            List<WomansProduct> products = db.WomansProducts.Where(c => c.Price <= price.PriceAmount && c.Brand.Category.MasterCategory.Id == price.MasterCategory.Id).ToList();
            return PartialView("~/Views/Shared/WomansProduct/_FilteredWomansProductList.cshtml", products);
        }
        public PartialViewResult WomansProductBySize(int id)
        {
            List<WomansProduct> products = db.WomansProducts.Where(c => c.Size.Id == id).ToList();
            return PartialView("~/Views/Shared/WomansProduct/_FilteredWomansProductList.cshtml", products);
        }
        public PartialViewResult WomansProductByColour(int id)
        {
            List<WomansProduct> products = db.WomansProducts.Where(c => c.Colour.Id==id).ToList();
            return PartialView("~/Views/Shared/WomansProduct/_FilteredWomansProductList.cshtml", products);
        }

        public ActionResult Index()
        {
            var womansProducts = db.WomansProducts.Include(w => w.Brand).Include(w => w.Colour).Include(w => w.Size);
            return View(womansProducts.ToList());
        }

        // GET: WomansProducts/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WomansProduct womansProduct = db.WomansProducts.Find(id);
            if (womansProduct == null)
            {
                return HttpNotFound();
            }
            return View(womansProduct);
        }

        // GET: WomansProducts/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands.Where(c=>c.Category.MasterCategory.Id==11).ToList(), "Id", "Name");
            ViewBag.ColourId = new SelectList(db.Colours.Where(c=>c.MasterCategory.Id==11).ToList(), "Id", "ColourName");
            ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle");
            return View();
        }

        // POST: WomansProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BrandId,SizeId,ColourId,Name,Image,Price,Description")] WomansProduct womansProduct,HttpPostedFileBase ImageFile)
        {
            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please upload an image");
                ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
                ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
                ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);
                return View(womansProduct);
            }
            bool IsValidFormat = common.ImageValidation(ImageFile);
            if (IsValidFormat == false)
            {
                ModelState.AddModelError("Image", "Only jpg, png, jpeg formates are allowed ");
                ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
                ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
                ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);
                return View(womansProduct);
            }
            byte[] convertedImage = common.ConvertImage(ImageFile);
            womansProduct.Image = convertedImage;
            if (ModelState.IsValid)
            {
                db.WomansProducts.Add(womansProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
            ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
            ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);
            return View(womansProduct);
        }

        // GET: WomansProducts/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WomansProduct womansProduct = db.WomansProducts.Find(id);
            if (womansProduct == null)
            {
                return HttpNotFound();
            }

            ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
            ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
            ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);

            return View(womansProduct);
        }

        // POST: WomansProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BrandId,SizeId,ColourId,Name,Image,Price,Description")] WomansProduct womansProduct,HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                bool IsValidFormate = common.ImageValidation(ImageFile);
                if (IsValidFormate == false)
                {
                    ModelState.AddModelError("Image", "Only jpg, png, jpeg formates are allowed ");
                    ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
                    ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
                    ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);
                    return View(womansProduct);
                }
                byte[] CurrentImage = common.ConvertImage(ImageFile);
                womansProduct.Image = CurrentImage;
            }
            if (ModelState.IsValid)
            {
                db.Entry(womansProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands.Where(c => c.Category.MasterCategory.Id == 11).ToList(), "Id", "Name", womansProduct.BrandId);
            ViewBag.ColourId = new SelectList(db.Colours.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "ColourName", womansProduct.ColourId);
            ViewBag.SizeId = new SelectList(db.Sizes.Where(c => c.MasterCategory.Id == 11).ToList(), "Id", "SizeTitle", womansProduct.SizeId);

            return View(womansProduct);
        }

        // GET: WomansProducts/Delete/5
        public JsonResult Delete(int id)
        {
            var ProductById = db.WomansProducts.Where(m => m.Id == id).FirstOrDefault();

            if (ProductById != null)
            {
                db.Entry(ProductById).State = EntityState.Deleted;
                int affectedRow = db.SaveChanges();

                if (affectedRow > 0)
                {
                    status = true;
                }
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

ClothesLine_FN/Views/WomansProducts/Create.cshtml
@model ClothesLine_FN.Models.WomansProduct

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "WomansProducts", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>WomansProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "Brand Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeId, "Size", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SizeId", null,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColourId, "Colour", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColourId", null,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColourId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="Image" />
                <br>
                <div class="col-md-3">
                    <div id="imagePreview" class="thumbnail" style="display:none">
                        <img class="img-responsive" id="TargetImage" />
                    </div>
                    <div class="">
                        <p id="Imagedescription"></p>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#Image").change(function () {
            var file = this.files;
            if (file && file[0]) {
                ReadImage(file[0]);
            }
        });
        var ReadImage = function (file) {
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                $("#TargetImage").attr("src", _file.target.result);
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;

                    var value = (file.size / 1024)
                    var size = Math.round(value * 100) / 100 + " KB";

                    $("#TargetImage").attr("src", _file.target.result);
                    $("#Imagedescription").html("Size: " + size + '</br>' + "Dimension: " + height + " × " + width);
                    $("#imagePreview").show();
                }
            }
        }
    </script>
}

ClothesLine_FN/Views/WomansProducts/Delete.cshtml
@model ClothesLine_FN.Models.WomansProduct

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WomansProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour.ColourName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour.ColourName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size.SizeTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size.SizeTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClothesLine_FN/Views/WomansProducts/Details.cshtml
@model ClothesLine_FN.Models.WomansProduct

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <br />
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>Product Details</h3>
        </div>
        <div class="panel-body">
            <div class="col-xs-10">
                <div class="row vertical-align">
                    <div class="col-xs-6">
                        @if (Model.Image != null)
                        {
                            string base64Image = Convert.ToBase64String(Model.Image);
                            string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                            <img class="img-responsive img-thumbnail img-rounded" src="@Image" width="450" height="450" />
                        }
                    </div>
                    <div class="col-xs-6">
                        <table class="table table-responsive">
                            <tr>
                                <td><h4>Product Name</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Name)</h4></td>
                            </tr>
                            <tr>
                                <td><h4>Brand Name</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Brand.Name)</h4></td>
                            </tr>
                            <tr>
                                <td><h4>Size</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Size.SizeTitle)</h4></td>
                            </tr>

                            <tr>
                                <td><h4>Colour </h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Colour.ColourName)</h4></td>
                            </tr>
                            <tr>
                                <td><h4>@Html.DisplayNameFor(model => model.Description)</h4></td>
                                <td><h4>@Html.DisplayFor(model => model.Description)</h4></td>
                            </tr>
                            <tr style="color:darkgreen">
                                <td><h4><b>@Html.DisplayNameFor(model => model.Price)</b></h4></td>
                                <td><h4><b>@Html.DisplayFor(model => model.Price)</b></h4></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-sm btn-primary" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-sm btn-info" })
</p>

ClothesLine_FN/Views/WomansProducts/Edit.cshtml
@model ClothesLine_FN.Models.WomansProduct

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "WomansProducts", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>WomansProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "BrandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeId, "SizeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SizeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColourId, "ColourId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColourId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColourId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <input type="file" name="ImageFile" id="Image" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                <br />
                @if (Model.Image != null)
                {
                    string base64Image = Convert.ToBase64String(Model.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" class="img-responsive" id="TargetImage" height="150" width="150" />
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        //this is for showing image immediately:
        $("#Image").change(function () {
            var file = this.files;
            if (file && file[0]) {
                ReadImage(file[0]);
            }
        });
        var ReadImage = function (file) {
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                $("#TargetImage").attr("src", _file.target.result);
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;

                    var value = (file.size / 1024)
                    var size = Math.round(value * 100) / 100 + " KB";

                    $("#TargetImage").attr("src", _file.target.result);
                    $("#Imagedescription").html("Size: " + size + '</br>' + "Dimension: " + height + " × " + width);
                    $("#imagePreview").show();
                }
            }
        }
    </script>
}

ClothesLine_FN/Views/WomansProducts/Index.cshtml
@model IEnumerable<ClothesLine_FN.Models.WomansProduct>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-sm btn-primary" })
</p>
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Brand.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colour.ColourName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size.SizeTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="DelRow_@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Brand.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Colour.ColourName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size.SizeTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @if (item.Image != null)
                    {
                        string base64Image = Convert.ToBase64String(item.Image);
                        string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                        <img src="@Image" width="100" height="100" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-primary" })
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                    <a class="btn btn-sm btn-danger delete_link" href="#" onclick="GetDeleteId(@item.Id)">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.Hidden("DeleteId")
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>

                <h4 class="modal-title">Delete Cofirmation</h4>
            </div>
            <div class="modal-body">
                <h5>Are you sure you want to delete this item?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <input type="button" class="btn btn-danger" value="Delete" id="btnConfirmDelete" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var GetDeleteId = function (Id) {
            $("#DeleteId").val(Id);
            $("#myModal").modal("show");
        }
        $("#btnConfirmDelete").on("click", function () {
            var deleteId = $("#DeleteId").val();
            $.ajax({
                url: "/WomansProducts/Delete",
                data: { id: deleteId },
                method: "post",
                success: function (response) {
                    if (response == 1) {
                        $("#myModal").modal("hide");
                        $("#DelRow_" + deleteId).remove();
                    }
                }
            })
        })
    </script>
}